🔧 add lhci workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -33,6 +33,12 @@ jobs:
       - name: Build
         run: yarn build
 
+       - name: Archive production artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: build-artifacts
+          path: ${{ github.workspace }}/.next
+
       - name: Bundle Watch
         shell: bash
         env: 
@@ -119,3 +125,25 @@ jobs:
         run: |
           yarn run knip > knipScanResult.txt 2>&1
           node ./scripts/knipScanReporter.js
+
+  lhci-scan:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v3
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: build-artifacts
+
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
+          NEXT_PUBLIC_MOCK: true
+
